# Site wide configuration

remote_theme: "mmistakes/minimal-mistakes"

title:            Sebastien Allgeyer
locale:           en_US
#ANU
url:  https://seballgeyer.github.io/allgeyer_s.github.io/
#Test Localhost
email: sebastien.allgeyer@gmail.com
skype: blabla
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
#markdown: redcarpet
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

plugins:
  - jekyll-remote-theme

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Sebastien Allgeyer
  avatar: seb.jpg
  bio: "I'm a postdoctoral fellow in geophysics based at the Australian National University"
  github: seballgeyer
  orcid: 0000-0003-4864-0181
  google:
    plus: 105701989260116665773
    scholar: ZOHPHngAAAAJ
  #google_plus: SebastienAllgeyer
  twitter: sebastienAll
  github: seballgeyer
  linkedin: seballgeyer
  email: sebastien.allgeyer@gmail.com
  researchgate: Sebastien_Allgeyer2
#  skype: u5260132@uds.anu.edu.au
#  wechat: blabla
scholar:
  style: assets/bibliography/mycslfile.csl
  locale: en

  sort_by: year
  order: descending

  source: assets/bibliography
  bibliography: mybiblio
  bibliography_template: bibtemplate

  replace_strings: true

#  details_dir:    pubs
#  details_layout: bib_details.html
#  details_link:   Details

  query: "@*"

  repository: ./pdf




include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
